// Sequential change detection on the per-rep drift score.
//
// Each scored rep's drift D_t is standardized against the athlete's in-control
// reference:      s_t = (D_t - mu0) / sigma0,   s̃_t = clip(s_t, ±outlierClip)
//
//   EWMA   Z_t = α·s̃_t + (1-α)·Z_{t-1}                 (Z_0 = 0)
//   CUSUM  C_t = max(0, C_{t-1} + s̃_t - k)              (C_0 = 0)
//   run_t  = consecutive reps with s̃ > warningThreshold  (persistence guard)
//
// Modes
//   ewma        alarm: Z > breakpointThreshold          warn: Z > warningThreshold
//   cusum       alarm: C > h                            warn: C > h/2
//   combined    alarm: Z > breakpointThreshold AND C > h
//               warn:  Z > warningThreshold OR C > h/2
//   consecutive alarm: ≥ max(1,m) consecutive reps with s̃ > breakpointThreshold
//               warn:  s̃ > warningThreshold            (naive baseline detector)
//
// For ewma/cusum/combined the alarm additionally requires run_t ≥ m
// (minimumPersistentReps; 0 disables). The BreakingPoint latches once fired.
// Onset (change-point) estimate = first rep of the current CUSUM excursion,
// i.e. the classic CUSUM "last time the statistic was zero" estimator.
//
// Unscored reps (null drift, e.g. poor capture) leave all state untouched.
// This file is mirrored line-for-line by lab/breakingpoint_lab/core.py and
// verified by tests/parity.test.ts against fixtures generated by the Lab.

import type { DetectorConfig } from './config';
import { clamp } from '../utils/stats';

export type MovementState = 'STABLE' | 'DRIFT' | 'BREAKPOINT';

export interface DetectorStep {
  rep: number;
  scored: boolean;
  score: number | null;
  s: number | null;
  sClipped: number | null;
  /** EWMA in reference-SD units. */
  ewma: number;
  /** EWMA mapped back to drift-score units: mu0 + sigma0·Z. */
  ewmaLevel: number;
  cusum: number;
  runLength: number;
  state: MovementState;
  /** True only on the rep where the BreakingPoint fired. */
  alarm: boolean;
}

export interface DriftThresholds {
  mu0: number;
  sigma0: number;
  /** Upper edge of the normal band (mu0 + 1·sigma0). */
  normalUpper: number;
  warningLevel: number;
  breakpointLevel: number;
}

type DetCfg = Pick<
  DetectorConfig,
  'mode' | 'ewmaAlpha' | 'cusumK' | 'cusumH' | 'warningThreshold' | 'breakpointThreshold' | 'minimumPersistentReps' | 'outlierClip'
>;

export class SequentialDetector {
  private z = 0;
  private c = 0;
  private run = 0;
  private runBp = 0;
  private onsetCandidate: number | null = null;
  state: MovementState = 'STABLE';
  alarmRep: number | null = null;
  onsetRep: number | null = null;
  firstWarnRep: number | null = null;
  readonly steps: DetectorStep[] = [];

  constructor(
    readonly cfg: DetCfg,
    readonly mu0: number,
    readonly sigma0: number,
  ) {}

  thresholds(): DriftThresholds {
    const { mu0, sigma0 } = this;
    return {
      mu0,
      sigma0,
      normalUpper: mu0 + sigma0,
      warningLevel: mu0 + this.cfg.warningThreshold * sigma0,
      breakpointLevel: mu0 + this.cfg.breakpointThreshold * sigma0,
    };
  }

  update(rep: number, score: number | null): DetectorStep {
    const cfg = this.cfg;
    if (score === null || !Number.isFinite(score)) {
      const step: DetectorStep = {
        rep,
        scored: false,
        score: null,
        s: null,
        sClipped: null,
        ewma: this.z,
        ewmaLevel: this.mu0 + this.sigma0 * this.z,
        cusum: this.c,
        runLength: this.run,
        state: this.state,
        alarm: false,
      };
      this.steps.push(step);
      return step;
    }

    const s = (score - this.mu0) / this.sigma0;
    const sc = cfg.outlierClip === null ? s : clamp(s, -cfg.outlierClip, cfg.outlierClip);
    this.z = cfg.ewmaAlpha * sc + (1 - cfg.ewmaAlpha) * this.z;
    const prevC = this.c;
    this.c = Math.max(0, this.c + sc - cfg.cusumK);
    if (this.c === 0) this.onsetCandidate = null;
    else if (prevC === 0) this.onsetCandidate = rep;
    this.run = sc > cfg.warningThreshold ? this.run + 1 : 0;
    this.runBp = sc > cfg.breakpointThreshold ? this.runBp + 1 : 0;

    let alarmCond: boolean;
    let warnCond: boolean;
    let persistOk = cfg.minimumPersistentReps <= 0 || this.run >= cfg.minimumPersistentReps;
    switch (cfg.mode) {
      case 'ewma':
        alarmCond = this.z > cfg.breakpointThreshold;
        warnCond = this.z > cfg.warningThreshold;
        break;
      case 'cusum':
        alarmCond = this.c > cfg.cusumH;
        warnCond = this.c > cfg.cusumH / 2;
        break;
      case 'consecutive':
        alarmCond = this.runBp >= Math.max(1, cfg.minimumPersistentReps);
        warnCond = sc > cfg.warningThreshold;
        persistOk = true;
        break;
      case 'combined':
      default:
        alarmCond = this.z > cfg.breakpointThreshold && this.c > cfg.cusumH;
        warnCond = this.z > cfg.warningThreshold || this.c > cfg.cusumH / 2;
        break;
    }

    let alarm = false;
    if (this.state !== 'BREAKPOINT') {
      if (alarmCond && persistOk) {
        this.state = 'BREAKPOINT';
        this.alarmRep = rep;
        this.onsetRep = this.onsetCandidate ?? rep;
        alarm = true;
      } else {
        this.state = warnCond ? 'DRIFT' : 'STABLE';
      }
      if (this.state !== 'STABLE' && this.firstWarnRep === null) this.firstWarnRep = rep;
    }

    const step: DetectorStep = {
      rep,
      scored: true,
      score,
      s,
      sClipped: sc,
      ewma: this.z,
      ewmaLevel: this.mu0 + this.sigma0 * this.z,
      cusum: this.c,
      runLength: this.run,
      state: this.state,
      alarm,
    };
    this.steps.push(step);
    return step;
  }
}

/** Convenience: run a whole drift sequence through a fresh detector. */
export function runDetector(cfg: DetCfg, mu0: number, sigma0: number, scores: readonly (number | null)[]): SequentialDetector {
  const det = new SequentialDetector(cfg, mu0, sigma0);
  scores.forEach((d, i) => det.update(i + 1, d));
  return det;
}
